version: "3"
services:
  app:
    container_name: go_app
    build: ./services/user/
    ports:
      - '8080:8080'
    restart: on-failure
    volumes:
      - ./services/user/:/app
    depends_on:
      - postgres-db
    networks:
      - go-network

  postgres-db:
    image: postgres:latest
    container_name: go_db
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - ./:/var/www/postgresql/data
    networks:
      - go-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: go_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres-db
    ports:
      - "5050:80"
    networks:
      - go-network
    restart: unless-stopped

networks:
  go-network:
    driver: bridge