version: "3"
services:
  app-user:
    container_name: app_user
    build: ./services/user/
    restart: on-failure
    volumes:
      - ./services/user/:/app/services/user
    depends_on:
      - postgres-db
      - nsqlookupd
      - nsqd
    networks:
      - go-network
  
  app-messaging:
    container_name: app_messaging
    build: ./services/messaging/
    restart: on-failure
    volumes:
      - ./services/messaging/:/app/services/messaging
    depends_on:
      - nsqlookupd
      - nsqd
    networks:
      - go-network

  app-ticket:
    container_name: app_ticket
    build: ./services/ticket/
    restart: on-failure
    volumes:
      - ./services/ticket/:/app/services/ticket
    networks:
      - go-network

  nginx:
    build: ./services/nginx/
    ports:
      - "8080:8080"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app-user
    networks:
      - go-network

  postgres-db:
    container_name: go_db
    build:
      context: .
      dockerfile: Dockerfile.postgre
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - ./:/var/www/postgresql/data
    networks:
      - go-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: go_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres-db
    ports:
      - "5050:80"
    networks:
      - go-network
    restart: unless-stopped

  nsqlookupd:
    image: nsqio/nsq
    container_name: app_nsqlookupd
    command: /nsqlookupd
    ports:
      - "4160:4161"
      - "4161:4161"
    networks:
      - go-network

  nsqd:
    image: nsqio/nsq
    container_name: app_nsqd
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
    networks:
      - go-network

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
    networks:
      - go-network

networks:
  go-network:
    driver: bridge